### ISSUE TITLE
p4aspaces doesn't work when run locally out of repository, only when installed system-wide [unintended limitation]

### ISSUE THREAD

**Issue by homdx** [JonasT/p4a-build-spaces#1]
Python2 error:
python ./p4aspaces.py --env p4a-py3-api18ndk21 --p4a master
  File "./p4aspaces.py", line 67
    file=sys.stderr, flush=True)
        ^
SyntaxError: invalid syntax

Python3:
python3 ./p4aspaces.py --env p4a-py3-api18ndk21 --p4a master
Traceback (most recent call last):
  File "./p4aspaces.py", line 12, in <module>
    from . import buildenv
ImportError: cannot import name 'buildenv'

```
# python3 setup.py install
running install
running bdist_egg
running egg_info
writing p4a_build_spaces.egg-info/PKG-INFO
writing dependency_links to p4a_build_spaces.egg-info/dependency_links.txt
writing entry points to p4a_build_spaces.egg-info/entry_points.txt
writing top-level names to p4a_build_spaces.egg-info/top_level.txt
reading manifest file 'p4a_build_spaces.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.py' under directory '*.txt'
warning: manifest_maker: MANIFEST.in, line 2: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

warning: no files found matching 'environments'
writing manifest file 'p4a_build_spaces.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying p4a_build_spaces.egg-info/PKG-INFO -> build/lib/p4aspaces/p4a_build_spaces.egg-info
copying p4a_build_spaces.egg-info/SOURCES.txt -> build/lib/p4aspaces/p4a_build_spaces.egg-info
copying p4a_build_spaces.egg-info/dependency_links.txt -> build/lib/p4aspaces/p4a_build_spaces.egg-info
copying p4a_build_spaces.egg-info/entry_points.txt -> build/lib/p4aspaces/p4a_build_spaces.egg-info
copying p4a_build_spaces.egg-info/top_level.txt -> build/lib/p4aspaces/p4a_build_spaces.egg-info
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/p4aspaces
copying build/lib/p4aspaces/__init__.py -> build/bdist.linux-x86_64/egg/p4aspaces
copying build/lib/p4aspaces/buildenv.py -> build/bdist.linux-x86_64/egg/p4aspaces
copying build/lib/p4aspaces/p4aspaces.py -> build/bdist.linux-x86_64/egg/p4aspaces
copying build/lib/p4aspaces/settings.py -> build/bdist.linux-x86_64/egg/p4aspaces
copying build/lib/p4aspaces/LICENSE.md -> build/bdist.linux-x86_64/egg/p4aspaces
copying build/lib/p4aspaces/MANIFEST.in -> build/bdist.linux-x86_64/egg/p4aspaces
copying build/lib/p4aspaces/README.md -> build/bdist.linux-x86_64/egg/p4aspaces
creating build/bdist.linux-x86_64/egg/p4aspaces/p4a_build_spaces.egg-info
copying build/lib/p4aspaces/p4a_build_spaces.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/p4aspaces/p4a_build_spaces.egg-info
copying build/lib/p4aspaces/p4a_build_spaces.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/p4aspaces/p4a_build_spaces.egg-info
copying build/lib/p4aspaces/p4a_build_spaces.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/p4aspaces/p4a_build_spaces.egg-info
copying build/lib/p4aspaces/p4a_build_spaces.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/p4aspaces/p4a_build_spaces.egg-info
copying build/lib/p4aspaces/p4a_build_spaces.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/p4aspaces/p4a_build_spaces.egg-info
creating build/bdist.linux-x86_64/egg/p4aspaces/environments
creating build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py2-api19-ndkbundle
copying build/lib/p4aspaces/environments/p4a-py2-api19-ndkbundle/Dockerfile -> build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py2-api19-ndkbundle
copying build/lib/p4aspaces/environments/p4a-py2-api19-ndkbundle/short_description.txt -> build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py2-api19-ndkbundle
creating build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py3-api28ndk21
copying build/lib/p4aspaces/environments/p4a-py3-api28ndk21/Dockerfile -> build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py3-api28ndk21
copying build/lib/p4aspaces/environments/p4a-py3-api28ndk21/short_description.txt -> build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py3-api28ndk21
creating build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py3crystax-api19-ndkbundle
copying build/lib/p4aspaces/environments/p4a-py3crystax-api19-ndkbundle/Dockerfile -> build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py3crystax-api19-ndkbundle
copying build/lib/p4aspaces/environments/p4a-py3crystax-api19-ndkbundle/short_description.txt -> build/bdist.linux-x86_64/egg/p4aspaces/environments/p4a-py3crystax-api19-ndkbundle
copying build/lib/p4aspaces/environments/test_app_instructions.txt -> build/bdist.linux-x86_64/egg/p4aspaces/environments
byte-compiling build/bdist.linux-x86_64/egg/p4aspaces/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/p4aspaces/buildenv.py to buildenv.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/p4aspaces/p4aspaces.py to p4aspaces.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/p4aspaces/settings.py to settings.cpython-36.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying LICENSE.md -> build/bdist.linux-x86_64/egg/
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying p4a_build_spaces.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying p4a_build_spaces.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying p4a_build_spaces.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying p4a_build_spaces.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying p4a_build_spaces.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
p4aspaces.__pycache__.buildenv.cpython-36: module references __file__
creating 'dist/p4a_build_spaces-0.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing p4a_build_spaces-0.1-py3.6.egg
creating /usr/local/lib/python3.6/site-packages/p4a_build_spaces-0.1-py3.6.egg
Extracting p4a_build_spaces-0.1-py3.6.egg to /usr/local/lib/python3.6/site-packages
Adding p4a-build-spaces 0.1 to easy-install.pth file
Installing p4aspaces script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/p4a_build_spaces-0.1-py3.6.egg
Processing dependencies for p4a-build-spaces==0.1
Finished processing dependencies for p4a-build-spaces==0.1
```
Env info:
```
$ python3 --version
Python 3.6.6
$ pip3 list 
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
decorator (4.2.1)
gpg (1.10.0)
iniparse (0.4)
IPy (0.81)
isc (2.0)
p4a-build-spaces (0.1)
pip (9.0.3)
ply (3.9)
pygobject (3.28.3)
python-augeas (0.5.0)
python-dmidecode (3.12.2)
pytoml (0.1.18)
PyYAML (3.12)
registries (0.1)
rpm (4.14.2)
sepolicy (1.1)
setools (4.1.1)
setuptools (39.2.0)
six (1.11.0)
slip (0.6.4)
slip.dbus (0.6.4)
smartcols (0.3.0)
sos (3.6)
SSSDConfig (1.16.3)
systemd-python (234)
```

**Comment by JonasT** [comment]
Yes, with a recent change the tool now *needs* to be installed system-wide because I couldn't make the relative import work for both non-installed and system-wide installed approaches, sorry about that.

So this is kind of annoying for sure, and I'd like to  get rid of it, but it's more of a fundamental problem than an accidental bug, and might need some thought to get working. (Open for suggestions)

Also, you need to run it with Python 3.x, I'll add a note for that to the README.md.

**Comment by homdx** [comment]
Solution:
[https://github.com/JonasT/p4a-build-spaces/pull/2](url)

**Comment by JonasT** [comment]
I'm a bit confused, that appears to be a `README.md` text change. How would that fix the import path issue?

**Comment by homdx** [comment]
Is this not related to the court sudo using in programm?
I can prepare a Dockerfile to reproduce this bug?

**Comment by JonasT** [comment]
I'm not sure what problem you are trying to solve. I thought it was this one:
```
$ ./p4aspaces.py 
Traceback (most recent call last):
  File "./p4aspaces.py", line 12, in <module>
    from . import buildenv
ImportError: cannot import name 'buildenv'
```
And that's not related to sudo, it's just the relative import not working in the repo.

**Comment by homdx** [comment]
probe with this Dockerfile
```
FROM fedora

RUN dnf update -y && dnf install git nano mc openssh-clients -y

RUN mkdir /app && cd /app && git clone https://github.com/JonasT/p4a-build-spaces.git \
&& cd p4a-build-spaces && python3 setup.py install

RUN cd /app/p4a-build-spaces && python ./p4aspaces.py --env p4a-py3-api18ndk21 --p4a master

```
log
```
$docker build -t test2 .
.... output skipped
Processing p4a_build_spaces-0.1-py3.7.egg
creating /usr/local/lib/python3.7/site-packages/p4a_build_spaces-0.1-py3.7.egg
Extracting p4a_build_spaces-0.1-py3.7.egg to /usr/local/lib/python3.7/site-packages
Adding p4a-build-spaces 0.1 to easy-install.pth file
Installing p4aspaces script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/p4a_build_spaces-0.1-py3.7.egg
Processing dependencies for p4a-build-spaces==0.1
Finished processing dependencies for p4a-build-spaces==0.1
 ---> 03c53f11e31a
Removing intermediate container ae662ed9f939
Step 5/6 : RUN cd /app/p4a-build-spaces && python ./p4aspaces.py --env p4a-py3-api18ndk21 --p4a master
 ---> Running in 6b5a1d470377
  File "./p4aspaces.py", line 71
    file=sys.stderr, flush=True)
        ^
SyntaxError: invalid syntax
The command '/bin/sh -c cd /app/p4a-build-spaces && python ./p4aspaces.py --env p4a-py3-api18ndk21 --p4a master' returned a non-zero code: 1
```

**Comment by homdx** [comment]
Dockerfile:
```
FROM fedora

RUN dnf update -y && dnf install git nano mc openssh-clients python3-virtualenv -y

RUN dnf install sudo python3-setuptools -y && adduser -m yourusername \
    && echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && groupadd sudo \
    && usermod -append --groups sudo yourusername \
    && mkdir /app && chown yourusername /app

USER yourusername

RUN cd /app && git clone https://github.com/JonasT/p4a-build-spaces.git \
&& cd p4a-build-spaces && sudo python3 setup.py install

#Next line get error ImportError: cannot import name 'buildenv' from '__main__' (./p4aspaces.py)
#RUN cd /app/p4a-build-spaces && sudo ./p4aspaces.py --env p4a-py3-api18ndk21 --p4a master


#Next line without error import name 'buildenv'
RUN   sudo pip3 install https://github.com/JonasT/p4a-build-spaces/archive/master.zip \
   && sudo p4aspaces --env p4a-py3-api28ndk21 --p4a master
```

If you uncomment line you give error:
```
Traceback (most recent call last):
  File "./p4aspaces.py", line 12, in <module>                                            
    from . import buildenv                                                               
ImportError: cannot import name 'buildenv' from '__main__' (./p4aspaces.py) 
```

if you run the file as given in this comment:
```
Traceback (most recent call last):
  File "/usr/local/bin/p4aspaces", line 11, in <module>                                  
    load_entry_point('p4a-build-spaces==0.1', 'console_scripts', 'p4aspaces')()          
  File "/usr/local/lib/python3.7/site-packages/p4a_build_spaces-0.1-py3.7.egg/p4aspaces/p4aspaces.py", line 67, in main                                                           
    stderr=subprocess.STDOUT)                                                            
  File "/usr/lib64/python3.7/subprocess.py", line 389, in check_output                   
    **kwargs).stdout                                                                     
  File "/usr/lib64/python3.7/subprocess.py", line 466, in run                            
    with Popen(*popenargs, **kwargs) as process:                                         
  File "/usr/lib64/python3.7/subprocess.py", line 769, in __init__                       
    restore_signals, start_new_session)                                                  
  File "/usr/lib64/python3.7/subprocess.py", line 1516, in _execute_child                
    raise child_exception_type(errno_num, err_msg, err_filename)                         
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker' 
```
You see that there is no import error buildenv.

But of course we will not build the docker application in the docker.

it's just about setting up the sudo

**Comment by JonasT** [comment]
You are using sudo in docker wrong completely unrelated  to this specific tool, and which isn't meant to be used in docker in the first place. I'm sorry, but there is no way this would make any sense to be added in a README, just use USER properly and you will be fine. (and again, this has absolutely nothing to do with p4-build-spaces, you would have the same problem with any other application in docker trying to abuse sudo like that) The other backtraces are in part because you ran it with Python 2. So can we leave all of that out and stick with the ImportError? Otherwise, we're just going to pile up unrelated backtraces without getting anywhere

**Comment by homdx** [comment]
Thank you. You can close this issue.

**Comment by JonasT** [comment]
The ImportError is now tracked in #3
