### ISSUE TITLE
The path python3.7 (from --python=python3.7) does not exist

### ISSUE THREAD

**Issue by homdx** [JonasT/p4a-build-spaces#4]
I probe compile python 3.7:

time p4a apk --arch=armeabi-v7a --name test --package com.example.test --version 1 --requirements=kivy,python3,paho-mqtt --private .

and have error:
```
[INFO]:    -> running virtualenv --python=python3.7 venv
           working: The path python3.7 (from --python=python3.7) does not exist                                           Exception in thread background thread for pid 20176:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_3: 

  RAN: /usr/local/bin/virtualenv --python=python3.7 venv

  STDOUT:
The path python3.7 (from --python=python3.7) does not exist


  STDERR:


Traceback (most recent call last):                                                                                        
  File "/usr/local/bin/p4a", line 11, in <module>
    load_entry_point('python-for-android==0.6.0', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 1033, in main
    ToolchainCL()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 553, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 150, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 191, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/build.py", line 655, in build_recipes
    run_pymodules_install(ctx, python_modules)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/build.py", line 676, in run_pymodules_install
    'venv')
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/logger.py", line 178, in shprint
    for line in output:
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 863, in next
    self.wait()
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_3: 

  RAN: /usr/local/bin/virtualenv --python=python3.7 venv

  STDOUT:
The path python3.7 (from --python=python3.7) does not exist
```

source code:
https://github.com/homdx/funcrash

[fun-crash.log](https://github.com/JonasT/p4a-build-spaces/files/2722224/fun-crash.log)

**Comment by johnbolia** [comment]
I am having a similar problem in this environment, I have tried the following in requirements:
python3==3.7
python==3.7
python3

All of them seem to be failing on the python3 download. I am on Ubuntu 18.10, do I need to be running python3.7 as host?

I thought python3==3.7 was the correct requirement, so I have included an error log from that.
[failed build on p4a-py3-api28ndk21.txt](https://github.com/JonasT/p4a-build-spaces/files/2723620/failed.build.on.p4a-py3-api28ndk21.txt)

**Comment by homdx** [comment]
@johnbolia please test with:
https://github.com/homdx/p4a-build-spaces/
_**branch**_ fix/python37

**Comment by JonasT** [comment]
Sorry, I must have missed this ticket in the notifications about other ones.

That is very fascinating! But why would it be hardcoded to python3.7? I am wondering if this is something that should be fixed in p4a...

> I am having a similar problem in this environment, I have tried the following in requirements:
> python3==3.7
> python==3.7
> python3

p4a tries to use python 3.7 on the *host*, for which the requirements don't do anything. It would need to be present in the docker image itself (which currently seems to have python 3.6) only - but I do wonder why p4a would be hardcoded to expect python 3.7 on the host. That seems like a very unfortunate and bad limitation, I wonder if it's intentional or rather an accident

**Comment by JonasT** [comment]
Fascinating, `python3.7` is not really referenced in the p4a code base. I wonder if this is a bug in the python 3 recipe that somehow derives that name from the downloaded manually cross-compiled python added into the apk?

**Comment by johnbolia** [comment]
@homdx  The branch fixed the problem and the apk built.

**Comment by JonasT** [comment]
Just to let you guys know, I just moved my app to exactly this environment and I'm doing a test build to see if I hit this. If yes I'll do a proper dig into p4a and see if this is really something that should be addressed in the environment or p4a itself. Shouldn't take me too long to figure out, hopefully

**Comment by JonasT** [comment]
Small update: python-for-android is a bit on fire right now due to a big merged refactor so I am currently dealing with 3-4 other bugs that stop me, but we should have it figured out soon so I can look at this issue specifically

**Comment by JonasT** [comment]
I'm working on an upstream fix for this issue here: https://github.com/kivy/python-for-android/pull/1577 (in python-for-android) Basically things break because the environment has python3.6 but p4a builds internally with 3.7, and makes an incorrect call assuming the minor versions always match
